name: Flaky Test CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up OpenJDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: Get Apollo repository
      uses: actions/checkout@v3
      with:
        repository: apolloconfig/apollo
        
    - name: Install and compile Apollo
      run: mvn clean install -DskipTests -pl apollo-biz -am
      
    - name: Run test w/o NonDex tool
      run: mvn -pl apollo-biz test -Dtest=com.ctrip.framework.apollo.biz.service.NamespaceBranchServiceTest#testUpdateBranchGrayRulesWithUpdateOnce
      
    - name: Run test w/ NonDex tool
      run: mvn -pl apollo-biz edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=com.ctrip.framework.apollo.biz.service.NamespaceBranchServiceTest#testUpdateBranchGrayRulesWithUpdateOnce
    